[build]
builder = "nixpacks"

[deploy]
startCommand = "node railway-deploy.js"
numReplicas = 1
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10 