[build]
builder = "nixpacks"

[deploy]
startCommand = "node railway-deploy.js"
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 5 